### ISSUE TITLE
Please add a revision to the formula due to libgit 2.1.4 replacing 2.1.3 in homebrew

### ISSUE THREAD

**Issue by CamJN** [MrAnno/homebrew-tap#10]
Homebrew updated libgit from 2.1.3 → 2.1.4, by default homebrew will update your formulae and remove old versions when you run any `brew` command unless you set several env vars opting out of this behaviour, which means that most homebrew users won't be able to use the bottle from this formula anymore.

Thanks for providing the formula with a bottle though, it's super convenient.

**Comment by MrAnno** [comment]
Thanks for opening this issue.

#11 bumps the revision.

**Comment by MrAnno** [comment]
@CamJN FYI official brew bottles are now available for Criterion.

See also Snaipe/Criterion#439
